- name: Install apt packages
  become: yes
  apt:
    update_cache: yes
    state: latest
    name: "{{ pkgs }}"

- name: Install rustup
  command: bash -l -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
  args:
    creates: "{{ ansible_env.HOME }}/.rustup"

- file:
    path: ~/.local/share/bash-completion/completions
    state: directory

- name: rustup completion
  command: bash -l -c "rustup completions bash > ~/.local/share/bash-completion/completions/rustup"

- name: Install components
  command: bash -l -c "rustup component add {{ components | join(' ') }}"

- name: Install rust-analyzer
  command: bash -l -c "rustup +nightly component add rust-analyzer-preview"

- name: Install crates
  command: bash -l -c "cargo install {{ item }}"
  with_items: "{{ crates }}"

- name: Use delta as default
  command: bash -l -c "git config --global {{ item }}"
  with_items:
    - pager.diff delta
    - pager.show delta
    - pager.log delta
    - pager.reflog delta
    - interactive.diffFilter 'delta --color-only'
    - delta.syntax-theme GitHub
