- name: Install apt packages
  become: yes
  apt:
    update_cache: yes
    state: latest
    name: "{{ pkgs }}"

- include_role:
    name: gantsign.golang
  vars:
    golang_gopath: '$HOME/go'

- name: Install go lint
  command: bash -l -c "go install -v -trimpath -ldflags '-s -w' github.com/golangci/golangci-lint/cmd/golangci-lint@latest"

- name: Install tools
  command: bash -l -c "go install {{ item }}"
  with_items: "{{ tools }}"
